### ISSUE TITLE
UC_OBJECTS_NOT_CONVERTIBLE

### ISSUE THREAD

**Issue by everton-demo** [tricktresor/sm30-mass-data-input#3]
Hi @Ennowulff ,

I tried to use your project for a load, but dump occurs when executing the VIEW_MAINTENANCE_GIVEN_DATA function:
![image](https://github.com/tricktresor/sm30-mass-data-input/assets/13936273/e29af381-eef2-49fd-9104-3c3cd734dd0b)

More precisely in the LSVIMF37 include, FILL_EXTRACT form:
![image](https://github.com/tricktresor/sm30-mass-data-input/assets/13936273/aa170f09-1141-4f92-b62b-38be261289ec)

My table has fields that are not of type CHAR or STRING:
![image](https://github.com/tricktresor/sm30-mass-data-input/assets/13936273/a8ef23f2-f0bd-47e6-934b-3ef853fc8ed5)

Does this prevent the use of the function, allowing only to load fields in text format, or is there any way around it?

Thanks!

**Comment by Ennowulff** [comment]
right. the FM VIEW_MAINTENANCE_GIVEN_DATA only supports char-like tables. I had to convert the input data to a "container".
See updated PROG ZTRCKTRSR_SM30_GIVEN_DATA
